### PR TITLE
Initial balance

### LINKED ISSUE #97: Balance level 1
# Problem statement

Using what we've learned so far about the difficulty, plus the level progression, level 1 needs to be balanced

# Definition of done
The following have been identified to be problems, so they need to be fixed and balanced around these issues:
- [x] Shorter time
- [x] Waypoint in the front is problematic as the UI bar covers the people
- [ ] Currently, Level 1 has the 4 characters, this has to change.

### PR DESCRIPTION
**Pull request by iSergioMejia**
Makes an initial balance of level 1. Of course it needs to be tested further and with more people

Closes #97

### CODE REVIEW

**Comment by theenergici** [comment]
did a couple test runs.
 I believe maybe adding a bit more people without masks would be better: There were some instances where I was waiting for people in WO masks that I believe were a bit too long.
 I do think I felt the waves. tbh they were very fun. maybe ether let the timer be 90s or add another wave. that could feel nice. 
 also I'm suspecting that the final wave(the one that spawns all the missing characters is a tiny bit too late in the scene).

**Review by Sebasgut1 — COMMENTED** [review]
I run it twice, I got max score easily. It is not hard, even I play with mousepad. I got three stars sparing 30 seconds. I would either reduce the range to get 3 stars or reduce the time of the match, just to feel that the level was hard enough. But it we leave this one as a tutorial, it is okay. Anyway, I have a bias, since I already played an unbalanced level while developing some stuff regarding the points. Maybe we should ask someone else to try it.

**Comment by namitopier** [comment]
So I have repeatedly started the level to test for different bugs and check the playability. Since I did that, of course, I've found many things to discuss about, but not necessarily all of them are that important to take into account.

First of all, I really loved the way the level is playable on both floors, it adds a sense of difficulty because you have to keep track of 2 different places together. Also, the different style of the characters is really cool to see. When a character is hit correctly, it really feels satisfying to see him going to the ground with such violence :)

Now, about my personal opinions and some bugs that I have found:
- The initial hint ("Welcome to GOU mall") should, in my opinion, pause the game or at least pause the countdown because took some time to read it the first time and I didn't like the fact that I was losing time while reading the game instructions;
- Right at the beginning of the level, while in the initial 3,2,1 countdown, the game is already running and if I spam the left click, I will start the level already with the boss angry. I know this could be a choice of game design, but I found it a little bit weird;
- After the click on the pause button, the game didn't seem to pause (the background was still running, one solution could be to cover all the background screen if it is difficult to stop all NPCs, so at least it really feels that it has stopped)
- Also about the pause, when resuming the game, the countdown stopped counting down XD
- On the pause HUD, the buttons to deactivate sound and music didn't work (but I think it is not implemented yet so no problem)
- IMO the three-star bar (at the center bottom of the screen) is a little too high, at many times it prevented me from clicking on characters passing through it (maybe make it so the click can pass through the bar?)
- The music starts really low in volume but increases a lot during its course
- I found it really hard to understand when an NPC is wearing a mask when it is facing away from the camera (like from the back), but I understand this can be an element of game design to make it harder

**Comment by JuanJoseJ** [comment]
Okay, I tried the game a few times and this is what I think:

- The bar with the stars hides a vital zone in the map where many characters concentrate.
- It was easy to get 2-3 stars, but most 2 stars situations were related to not having enough characters to shoot, rather than missing them, it should always be possible to get 3 stars.
- The boss's anger is basically useless, to the point where I would rather shoot a character if Im looking at it from the back and I can't see if it's wearing a mask, than missing the points.
- The text box with info about the characters and the game comes in the middle of the level and covers a big chunk of the screen, making me run to close it rather than wanting to read it.

**Pull request merged**
