### PR TITLE
115 made script to activate and deactivate pause when ESC button is pressed

### PR DESCRIPTION
**Pull request by theenergici**

### CODE REVIEW

**Review by iSergioMejia — CHANGES_REQUESTED** [review]
I tested it and it works for the basic case, but if I press a bit too long the key it doesn't pause (which _could_ be ok) but the problem is that after that I cannot use the key to pause it again.
Same behaviour when I press the key twice in quick succession

**Comment by theenergici** [comment]
> I tested it and it works for the basic case, but if I press a bit too long the key it doesn't pause (which _could_ be ok) but the problem is that after that I cannot use the key to pause it again. Same behaviour when I press the key twice in quick succession

Added a cooldown when pressing, so multiple presses don't interfere with each other. 
it should work as soon as you press independent if you keep it pressed.  (it just checks the first frame of the click, if you keep it it doesnt matter)
also added a fix that should have been done with the prefab of the UI, but it didnt. causing conflicts with manual presses of the continue button on UI.

**Review by iSergioMejia — CHANGES_REQUESTED** [review]
If I left the ESC key pressed without releasing it (or releasing it after a certain amount of time) bugs it and now I can't use it anymore unless I manually click the button. Should the logic of clicking a key be this complex?

**Comment by theenergici** [comment]
> If I left the ESC key pressed without releasing it (or releasing it after a certain amount of time) bugs it and now I can't use it anymore unless I manually click the button. Should the logic of clicking a key be this complex?

Tbh, it shouldn't. Trying it in my end it doesn't  behave as such. 
The function used doesn't take into account the time you press it, just the first frame.
I tried to reproduce the bug you say, but it doesn't happen in my end.
If i had to guess what happens is that your key interprets it as multiple click rather than 1 long click.

**Review by iSergioMejia — APPROVED** [review]

**Pull request merged**
